### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by nfleury** [ccollicutt/docker-swift-onlyone#1]
I just followed the examples, everything seems to fo fine but I cannot get this to work:

swift -A http://127.0.0.1:{myport}/auth/v1.0 -U test:tester -K testing stat

Should I do something else (add the user) or is this supposed to work with current configuration ?

I keep having this error on client : 

Traceback (most recent call last):
  File "/usr/local/bin/swift", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/shell.py", line 1287, in main
    globals()['st_%s' % args[0]](parser, argv[1:], output)
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/shell.py", line 492, in st_stat
    stat_result = swift.stat()
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/service.py", line 443, in stat
    raise SwiftError('Account not found', exc=err)
swiftclient.service.SwiftError: 'Account not found'

There does not seem to be any error on the container side on each request

Any idea ?

**Comment by ccollicutt** [comment]
If you look at the logs for the container it might show the password. I think I forgot to update the readme. It's probably setting it to a random value and printing it to the logs. I'll try to update the readme today.

**Comment by MorrisJobke** [comment]
Same here.

The output is something like this:

```
$ docker logs CONTAINER | grep user
user_test_tester = zahjeuquaixa .admin
user_test2_tester2 = zahjeuquaixa .admin
user_test_tester3 = zahjeuquaixa
```

Then the key for the user `test:tester` is `zahjeuquaixa`?

**Comment by ccollicutt** [comment]
Should be yeah, not completely sure what you are asking though.

**Comment by MorrisJobke** [comment]
I'm just new to that swift world. And I just want to clarify if the user name doesn't have changed from `test:tester` to `test_tester` or something like that ;)

**Comment by scottfrederick** [comment]
I was just trying to figure this out too. 

Do as @MorrisJobke says and use `docker logs` to get the generated password: 

```
$ docker logs CONTAINER | grep user
user_test_tester = zahjeuquaixa .admin
user_test2_tester2 = zahjeuquaixa .admin
user_test_tester3 = zahjeuquaixa
```

In this example the password is `zahjeuquaixa`, so you would use that for the `-K` argument: 

```
vagrant@host1:~$ swift -A http://127.0.0.1:12345/auth/v1.0 -U test:tester -K zahjeuquaixa stat
```

**Comment by antono** [comment]
The problem was fixed here https://github.com/ccollicutt/docker-swift-onlyone/commit/c9f5e41b745eee18e7ddc807481bc9729d8cdac0#diff-65e9e736b090429a7452b9be97fc8a1d 

Not yet published. You can pull antono/swift-onlyone image meanwhile with fixed script.

**Comment by ccollicutt** [comment]
Great thanks @antono, that is a silly mistake in the script!

**Comment by ccollicutt** [comment]
Finally took a look at this again and changed a few things which fix this.
