### ISSUE TITLE
fyi - works fine with ext4

### ISSUE THREAD

**Issue by jeacott** [ccollicutt/docker-swift-onlyone#5]
for anyone who might be interested, serverascode/swift-onlyone images works just fine on ext4, so no particularly special filesystem required. I'm running it on a mapped path, not a docker volume, also works just fine.
being new to swift it took me a little while to figure out the connection requirements, but its an excellent project and I'd love to see an updated version.

thanks!

**Comment by ccollicutt** [comment]
Cool thanks @jeacott. I should do some work on this, but I'm not sure I'll have time. Thanks again for the info!
